const seedState = {
  cars: [
    { id: 'c1', plateNumber: 'B 123 ABC', brand: 'Dacia', model: 'Logan', year: 2021, fuelType: 'Benzină/GPL', status: 'Activ', isListed: false },
    { id: 'c2', plateNumber: 'CJ 77 WXY', brand: 'Skoda', model: 'Octavia', year: 2019, fuelType: 'Motorină', status: 'Activ', isListed: false },
    { id: 'c3', plateNumber: 'TM 99 ZZZ', brand: 'Volkswagen', model: 'Golf', year: 2022, fuelType: 'Electric', status: 'În Service', isListed: false },
    { id: 'c4', plateNumber: 'IS 05 SMW', brand: 'Ford', model: 'Focus', year: 2020, fuelType: 'Hibrid', status: 'În Service', isListed: false },
    {
      id: 's1', plateNumber: 'B 00 BMW', brand: 'BMW', model: '7 Series', year: 2022, fuelType: 'Mild Hybrid', status: 'Activ',
      category: 'Sedan Premium', price: 34900, mileage: 62000, transmission: 'Automat',
      imageUrl: 'images/luxury_silver_sedan.png',
      description: 'BMW Seria 7 în finisaj argintiu metalizat, echipare completă cu tehnologie mild-hybrid, confort de limuzină și istoric de service verificat.',
      specs: { 'Cai Putere': '394 CP', Transmisie: 'Automată 8 trepte', Culoare: 'Silver Metallic', Garanție: '12 Luni incluse' },
      financingMonthly: 450, isListed: true, badge: 'Disponibil',
    },
    {
      id: 's2', plateNumber: 'B 00 RRV', brand: 'Range Rover', model: 'Velar', year: 2023, fuelType: 'Plug-In Hybrid', status: 'Activ',
      category: 'SUV Luxury', price: 62500, mileage: 34000, transmission: 'Automat',
      imageUrl: 'images/dark_metal_suv.png',
      description: 'Range Rover Velar combină designul britanic cu tehnologia Plug-In Hybrid, interior premium și tracțiune integrală inteligentă.',
      specs: { 'Cai Putere': '404 CP', Transmisie: 'Automată 8 trepte', Capacitate: '5 Locuri', Garanție: '12 Luni incluse' },
      financingMonthly: 790, isListed: true, badge: 'Disponibil',
    },
    {
      id: 's3', plateNumber: 'B 00 AM', brand: 'Aston Martin', model: 'Valkyrie', year: 2021, fuelType: 'Benzină', status: 'Activ',
      category: 'Sports Premium', price: 119000, mileage: 18500, transmission: 'Automat (PDK)',
      imageUrl: 'images/grey_sports_car.png',
      description: 'Aston Martin Valkyrie — hypercar de ediție limitată, performanțe extreme și finisaje handcrafted, pentru colecționari exigenți.',
      specs: { 'Cai Putere': '1160 CP', Transmisie: 'Automată 7 trepte', '0-100 km/h': '2.5 secunde', Garanție: '12 Luni incluse' },
      financingMonthly: 1450, isListed: true, badge: 'Disponibil',
    },
    {
      id: 's4', plateNumber: 'B 01 MER', brand: 'Mercedes-Benz', model: 'S-Class 580', year: 2023, fuelType: 'Hibrid', status: 'Activ',
      category: 'Sedan Premium', price: 98500, mileage: 22000, transmission: 'Automat 9G-TRONIC',
      imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?auto=format&fit=crop&w=900&q=80',
      description: 'Mercedes-Benz S-Class — referința segmentului luxury, cu sistem MBUX Hyperscreen și confort rear executive.',
      specs: { 'Cai Putere': '503 CP', Transmisie: 'Automată 9 trepte', Culoare: 'Obsidian Black', Garanție: '12 Luni incluse' },
      financingMonthly: 1180, isListed: true, badge: 'Disponibil',
    },
      id: 's5', plateNumber: 'B 02 AUD', brand: 'Audi', model: 'e-tron GT quattro', year: 2024, fuelType: 'Electric', status: 'Activ',
      category: 'Sports Premium', price: 87500, mileage: 12000, transmission: 'Automat',
      imageUrl: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=900&q=80',
      description: 'Audi e-tron GT — coupe electric de performanță cu design agresiv și autonomie extinsă.',
      specs: { 'Cai Putere': '646 CP', Autonomie: '488 km WLTP', Transmisie: 'Automată 2 trepte', Garanție: '12 Luni incluse' },
      financingMonthly: 1050, isListed: true, badge: 'Disponibil',
    },
    {
      id: 's6', plateNumber: 'B 03 TSL', brand: 'Tesla', model: 'Model S Plaid', year: 2023, fuelType: 'Electric', status: 'Activ',
      category: 'Sedan Premium', price: 79900, mileage: 28000, transmission: 'Automat',
      imageUrl: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=900&q=80',
      description: 'Tesla Model S Plaid — accelerare record, tehnologie Autopilot avansat și interior minimalist premium.',
      specs: { 'Cai Putere': '1020 CP', Autonomie: '600 km WLTP', '0-100 km/h': '2.1 secunde', Garanție: '12 Luni incluse' },
      financingMonthly: 960, isListed: true, badge: 'Disponibil',
    },
    {
      id: 's7', plateNumber: 'B 04 LAM', brand: 'Lamborghini', model: 'Urus Performante', year: 2022, fuelType: 'Benzină', status: 'Activ',
      category: 'SUV Luxury', price: 249000, mileage: 15000, transmission: 'Automat 8 trepte',
      imageUrl: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?auto=format&fit=crop&w=900&q=80',
      description: 'Lamborghini Urus Performante — SUV super sport cu motor V8 biturbo și dinamică de supercar.',
      specs: { 'Cai Putere': '666 CP', Transmisie: 'Automată 8 trepte', '0-100 km/h': '3.3 secunde', Garanție: '12 Luni incluse' },
      financingMonthly: 2990, isListed: true, badge: 'Disponibil',
    },
    {
      id: 's8', plateNumber: 'B 05 BEN', brand: 'Bentley', model: 'Continental GT Speed', year: 2021, fuelType: 'Benzină', status: 'Activ',
      category: 'Sports Premium', price: 189000, mileage: 21000, transmission: 'Automat 8 trepte',
      imageUrl: 'https://images.unsplash.com/photo-1606016159991-dfe4f2746ad5?auto=format&fit=crop&w=900&q=80',
      description: 'Bentley Continental GT Speed — grand tourer britanic cu finisaje din piele Mulliner și motor W12.',
      specs: { 'Cai Putere': '659 CP', Transmisie: 'Automată 8 trepte', Interior: 'Piele Beluga', Garanție: '12 Luni incluse' },
      financingMonthly: 2270, isListed: true, badge: 'Disponibil',
    },
    {
      id: 's9', plateNumber: 'B 06 LEX', brand: 'Lexus', model: 'LX 600 Ultra Luxury', year: 2023, fuelType: 'Benzină', status: 'Activ',
      category: 'SUV Luxury', price: 112000, mileage: 19000, transmission: 'Automat 10 trepte',
      imageUrl: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=80',
      description: 'Lexus LX 600 Ultra Luxury — SUV flagship cu 7 locuri, confort orient spre off-road premium și fiabilitate legendară.',
      specs: { 'Cai Putere': '409 CP', Transmisie: 'Automată 10 trepte', Capacitate: '7 Locuri', Garanție: '12 Luni incluse' },
    },
  ],
  drivers: [
    { id: 'd1', name: 'Andrei Ionescu', licenseCategory: 'B', phone: '0722123456', licenseExpiry: '2028-10-12', assignedCarId: 'c1' },
    { id: 'd2', name: 'Mihai Popescu', licenseCategory: 'B, C', phone: '0733987654', licenseExpiry: '2026-06-15', assignedCarId: 'c2' },
    { id: 'd3', name: 'Elena Dumitrescu', licenseCategory: 'B', phone: '0744112233', licenseExpiry: '2029-01-20', assignedCarId: 'c4' },
    { id: 'd4', name: 'Alexandru Radu', licenseCategory: 'B', phone: '0755443322', licenseExpiry: '2026-08-30', assignedCarId: 'c3' },
  ],
  service: [
    { id: 's1', carId: 'c3', date: '2026-05-20', description: 'Schimb filtre și ulei motor + revizie sistem electric', cost: 850, status: 'În curs' },
    { id: 's2', carId: 'c1', date: '2026-04-10', description: 'Înlocuire plăcuțe frână față și lichid de frână', cost: 450, status: 'Finalizat' },
    { id: 's3', carId: 'c2', date: '2026-03-05', description: 'Kit distribuție și pompă de apă', cost: 1800, status: 'Finalizat' },
  ],
  insurances: [
    { id: 'i1', carId: 'c1', type: 'RCA', company: 'Euroins', cost: 1200, startDate: '2025-06-01', expiryDate: '2026-06-01' },
    { id: 'i2', carId: 'c2', type: 'CASCO', company: 'Omniasig', cost: 3400, startDate: '2025-09-15', expiryDate: '2026-09-15' },
    { id: 'i3', carId: 'c3', type: 'RCA', company: 'Groupama', cost: 950, startDate: '2026-01-10', expiryDate: '2027-01-10' },
    { id: 'i4', carId: 'c4', type: 'RCA', company: 'Allianz Direct', cost: 1100, startDate: '2026-05-25', expiryDate: '2026-06-25' },
  ],
  vignettes: [
    { id: 'v1', carId: 'c1', country: 'România', duration: '1 An', startDate: '2025-08-01', expiryDate: '2026-08-01', cost: 140 },
    { id: 'v2', carId: 'c2', country: 'România', duration: '1 An', startDate: '2025-11-20', expiryDate: '2026-11-20', cost: 140 },
    { id: 'v3', carId: 'c3', country: 'Ungaria', duration: '10 Zile', startDate: '2026-05-24', expiryDate: '2026-06-03', cost: 80 },
    { id: 'v4', carId: 'c4', country: 'România', duration: '30 Zile', startDate: '2026-04-28', expiryDate: '2026-05-28', cost: 35 },
  ],
  tires: [
    { id: 't1', carId: 'c1', season: 'Vară', size: '185/65 R15', brand: 'Michelin', state: 'Excelent', location: 'Pe mașină' },
    { id: 't2', carId: 'c1', season: 'Iarnă', size: '185/65 R15', brand: 'Continental', state: 'Uzat', location: 'Depozit' },
    { id: 't3', carId: 'c2', season: 'All-Season', size: '205/55 R16', brand: 'Bridgestone', state: 'Bun', location: 'Pe mașină' },
    { id: 't4', carId: 'c3', season: 'Vară', size: '195/65 R15', brand: 'Hankook', state: 'Nou', location: 'Pe mașină' },
    { id: 't5', carId: 'c4', season: 'Iarnă', size: '205/55 R16', brand: 'Nokian', state: 'Excelent', location: 'Pe mașină' },
  ],
  users: [
    { username: 'admin', parola: 'admin123', rol: 'admin', passkey: 'key_admin_master' },
    { username: 'andrei', parola: 'client123', rol: 'client', driverId: 'd1', passkey: 'key_andrei_default' },
    { username: 'mihai', parola: 'client123', rol: 'client', driverId: 'd2', passkey: 'key_mihai_default' },
    { username: 'elena', parola: 'client123', rol: 'client', driverId: 'd3', passkey: 'key_elena_default' },
    { username: 'alexandru', parola: 'client123', rol: 'client', driverId: 'd4', passkey: 'key_alexandru_default' },
  ],
};

export default seedState;
